<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>InvoiceMaster.Tests</RootNamespace>
    <AssemblyName>invoicemaster.tests</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StartupObject>InvoiceMaster.Tests.TestRunner</StartupObject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../src/**/*.cs" />
    <Compile Include="TestRunner.cs" />
  </ItemGroup>

</Project>
